export const links = {
  source: 'https://github.com/try-auroraview/auroraview',
  docs: 'https://try-auroraview.github.io/auroraview/',
  releases: 'https://github.com/try-auroraview/auroraview/releases/latest',
  sdk: 'https://github.com/try-auroraview/auroraview/tree/main/packages/auroraview-sdk',
  examples: 'https://github.com/try-auroraview/auroraview/tree/main/examples',
  gallery: 'https://github.com/try-auroraview/auroraview/tree/main/gallery',
  organization: 'https://github.com/try-auroraview',
  mayaOutliner: 'https://github.com/try-auroraview/auroraview-maya-outliner',
};

export const content = {
  en: {
    lang: 'en', locale: 'en_US', other: '/zh/', otherLabel: '简体中文',
    title: 'AuroraView | Web interfaces for creative software',
    description: 'Build web interfaces for DCC tools with AuroraView. Explore the Rust core, Python API, TypeScript SDK, host adapters, runnable examples, and integration status.',
    skip: 'Skip to content', nav: ['Why AuroraView', 'Architecture', 'Projects', 'Get started'], theme: 'Switch color theme', light: 'Light', dark: 'Dark',
    heroLabel: 'AURORAVIEW / OPEN SOURCE', hero: 'Web interfaces.<br>Native workflows.',
    intro: 'Build polished interfaces with your frontend stack and AI coding tools. Connect them to native creative software.',
    start: 'Start building', explore: 'Explore projects', heroAlt: 'Concept illustration of web interfaces and structured agent contracts connected to a native creative workspace, extensions, and packaging.',
    concept: 'Concept illustration. Not a running application screenshot.',
    facts: [['Rust', 'Native core and WebView backends'], ['Python 3.7+', 'API for existing DCC environments'], ['TypeScript', 'Framework-agnostic frontend SDK']],
    whyTitle: 'Web UI is easier to build.<br>The host still needs a proper bridge.',
    whyIntro: 'AI coding assistants make web interfaces faster to explore and refine. Bringing that work into Maya, Houdini, or a game engine still means dealing with native windows, UI threads, packaging, and application APIs. AuroraView gives those responsibilities a shared framework and clear boundaries.',
    problems: [
      ['Build with the web ecosystem', 'Use HTML, CSS, React, or Vue for panels, asset browsers, and pipeline tools. Let people and coding agents work with familiar components while keeping host operations separate.'],
      ['Give the bridge a contract', 'Call host methods and receive events through a shared SDK. Keep application logic in Python or a native adapter instead of scattering it through the page.'],
      ['Respect the host', 'Docking, UI threads, focus, and shutdown belong to the host integration. Sharing a protocol does not make every host or platform behave the same.'],
    ],
    whyAlt: 'Concept illustration contrasting repeated interface fragments with one web interface connected to separate native host bridges.',
    builtTitle: 'A working foundation, with source you can inspect.',
    builtIntro: 'The main project contains the native core, Python package, frontend SDK, CLI, and Gallery app. It also contains browser APIs, an extension compatibility layer, and packing tools. Release assets include wheels, command-line tools, and Gallery builds.',
    galleryAlt: 'Existing AuroraView Gallery sample showing navigation, getting-started links, code samples, and sample search.',
    galleryCaption: 'Existing Gallery sample from the main repository. This image is a project asset, not a new host acceptance test.',
    sourceLabel: 'Read the source', releaseLabel: 'Download release assets', galleryLabel: 'Browse the Gallery source',
    architectureTitle: 'Current source.<br>Shared contracts and host boundaries.',
    architectureIntro: 'People use the web interface. Agents enter through an explicitly configured DCC-MCP adapter. Both rely on declared contracts; the native host keeps ownership of its lifecycle and scene API.',
    layers: [
      ['People and web interface', 'HTML / CSS / React / Vue', 'Presentation and direct interaction with the tool.'],
      ['Declared entry points', 'TypeScript SDK / optional DCC-MCP registration', 'Web calls and events; configured agent tools and session identity.'],
      ['AuroraView core and APIs', 'Rust · IPC · Python / PyO3 · WebView backends', 'Shared communication, window integration, and backend abstractions.'],
      ['Optional browser and extension capabilities', 'Browser APIs · extension host · plugins', 'Optional capabilities remain separate from scene semantics and host lifecycle.'],
      ['Native host adapter', 'Python + Qt / native engine integration', 'Host API calls, docking, UI-thread dispatch, focus, and shutdown.'],
    ],
    hostBoundary: 'The application owns its UI thread and lifecycle.',
    hostDetail: 'Qt-based DCCs can share Qt integration. Blender, Unreal, and Unity need their own host boundaries. On Windows, WebView2 objects remain on their owning STA thread.',
    packBoundary: 'Pack and distribution', packDetail: 'Build-time path: bundle frontend assets, Python services, and native startup for a chosen target. Packing does not replace runtime host integration.',
    diagramSource: 'Download editable architecture (.drawio)', architectureDocs: 'Read the architecture guide',
    agentTitle: 'One tool for people.<br>Explicit contracts for agents.',
    agentIntro: 'The aim is to make a useful tool available through both a clear interface and a deliberate agent entry point. The current DCC-MCP integration supplies a small, inspectable starting surface.',
    humanTitle: 'People use the interface', humanDetail: 'Build the controls and feedback your workflow needs. The SDK connects the page to declared host methods and events.',
    agentPathTitle: 'Agents use registered capabilities', agentDetail: 'Install the optional dcc-mcp-core dependency, configure AuroraViewAdapter, and start its server. FileRegistry registration makes that running session discoverable.',
    agentTools: 'Current adapter tools', agentContext: 'Session context: window title, URL, PID, CDP port, and detected host. Scene-specific tools and context require additional host or Skill registration; they are not inferred automatically from the UI.',
    agentSource: 'Inspect the DCC-MCP integration', agentNote: 'Source implementation describes the available contract. It is separate from a verified agent interaction in a particular host.',
    runtimeLabel: 'PROPOSED / SHARED RUNTIME', runtimeTitle: 'One host capability.<br>A page and an agent can both use it.',
    runtimeIntro: 'The integration direction keeps AuroraView focused on modern web interfaces, rendering, frontend events, and native presentation. A thin layer would reuse DCC-MCP Core’s server, tool and Skill registry, execution bridge, and service lifecycle. This integration has not yet been delivered.',
    runtimeLayers: [
      ['AuroraView', 'WebView · HTML and assets · frontend bridge · native docking', 'Own the interface and rendering. Browser capabilities, extensions, and build-time packing retain their own boundaries.'],
      ['Thin integration layer / proposed', 'Explicit calls and events · attachment · resource ownership', 'Map page calls to declared tools and connect their events. Page and Agent should reuse the same host business capability.'],
      ['DCC-MCP Core / existing infrastructure', 'Server / MCP · tools and Skills · execution bridge · lifecycle', 'Reuse existing host services and scheduling through public contracts. This is a design direction for AuroraView integration, not a newly delivered API.'],
      ['Native host adapter', 'Main-thread dispatch · scene API · native windows · event loop', 'Keep application-specific operations and host ownership explicit. Read back the same host instance from the page and the Agent.'],
    ],
    runtimeOwnership: 'Attach first. Release what you own.',
    runtimeOwnershipDetail: 'Prefer attaching to an existing DCC-MCP host service; create missing resources when needed. Closing a panel should release its subscriptions, connections, and tasks while leaving borrowed host services running. Creators must fully close resources they own, and shutdown must be repeatable.',
    runtimePending: 'Still to implement and validate: version compatibility, event and error mapping, service ownership, reconnect behavior, native docking, and real-host interaction. No measured backend reuse percentage is claimed.',
    runtimeSource: 'Proposed integration (.drawio)', runtimeSvg: 'Proposed diagram (SVG)', runtimePng: 'Proposed diagram (PNG)', runtimeCore: 'DCC-MCP Core source',
    capabilityTitle: 'Beyond a single embedded panel.',
    capabilities: [
      ['Browser-like APIs', 'The SDK exposes browser-oriented surfaces for tabs, windows, storage, runtime messages, and more. Available behavior depends on the backend and enabled features.', 'packages/auroraview-sdk/src'],
      ['Extensions and plugins', 'Dedicated crates manage extension lifecycle, manifests, messaging, and browser API compatibility. Treat compatibility as API-specific, not a promise that every Chrome extension runs unchanged.', 'crates/auroraview-extensions'],
      ['Pack and distribute', 'Packing separates frontend assets, Python services, and native application startup. Choose the deployment strategy for the target environment and validate the resulting artifact.', 'crates/auroraview-pack'],
    ],
    projectsTitle: 'An ecosystem organized around the host.',
    projectsIntro: 'Start with the core, then choose the adapter and example for your application. Repository availability is listed separately from live-host validation.',
    projectHeaders: ['Project', 'Responsibility', 'Current evidence'],
    projects: [
      ['auroraview', 'Core, Python API, SDK, CLI, and Gallery', 'Source and published release assets', links.source],
      ['auroraview-maya', 'Maya host adapter', 'Adapter source; host acceptance is version-specific', 'https://github.com/try-auroraview/auroraview-maya'],
      ['auroraview-maya-outliner', 'Independent Maya scene-tree teaching project', 'Source available; tutorial refresh and host acceptance in progress', links.mayaOutliner],
      ['auroraview-houdini', 'Houdini host adapter', 'Adapter source; host acceptance is version-specific', 'https://github.com/try-auroraview/auroraview-houdini'],
      ['auroraview-nuke', 'Nuke dispatcher and host adapter', 'Adapter source; host acceptance is version-specific', 'https://github.com/try-auroraview/auroraview-nuke'],
      ['auroraview-blender', 'Native Blender add-on and experimental WebView path', 'Experimental; native WebView docking acceptance tracked separately', 'https://github.com/try-auroraview/auroraview-blender'],
      ['auroraview-unreal', 'Unreal Engine integration', 'Experimental; native build and interactive acceptance tracked separately', 'https://github.com/try-auroraview/auroraview-unreal'],
    ],
    evidenceTitle: 'What “verified” means here',
    evidence: 'Source, automated tests, native builds, real-host launch, and interactive demos are different milestones. A repository or a passing unit test does not establish complete host support. Check each adapter’s documented environment before adopting it.',
    evidenceDate: 'Project map reviewed 8 October 2026. Follow repository validation records for newer results.',
    startTitle: 'Start outside the host.<br>Then bring your tool inside.',
    startIntro: 'First load your frontend in a standalone window. Then select a host adapter, keep host operations behind its API, and validate the full lifecycle in your target application.',
    installLabel: '1 / Install the Python package', codeLabel: '2 / Load your local frontend', copy: 'Copy', copied: 'Copied', copyFailed: 'Select and copy the code manually.',
    prerequisites: 'Use the Python environment for your intended host. Windows needs the WebView2 Runtime; Linux needs WebKitGTK system dependencies. Qt integration has its own host requirements.',
    docLabel: 'Installation and platform prerequisites',
    tutorialsTitle: 'Learn from a real tool.',
    tutorialsIntro: 'Keep small, runnable teaching projects alongside the host adapters. Each example should name its prerequisites, launch command, expected behavior, and validation limits.',
    tutorials: [
      ['Maya Outliner', 'A separate scene-tree example for Maya. The runnable tutorial is being refreshed; interactive host acceptance is still pending.', 'Explore the teaching project', links.mayaOutliner],
      ['Core examples', 'Standalone windows, calls, events, and Qt integration patterns.', 'Browse examples', links.examples],
      ['Gallery', 'Explore the existing demo app and the code behind its interface.', 'Open Gallery source', links.gallery],
    ],
    contributing: 'Building a host integration?', contribution: 'Keep the shared protocol small. Put host lifecycle and packaging in the adapter, and include a runnable example with explicit validation evidence.', contributionLink: 'Contribute on GitHub',
    footer: 'Open-source web interfaces for creative software.', credits: 'Media sources and credits', privacy: 'No analytics or third-party requests. Fonts and images are served with the site.',
    mediaTitle: 'Media sources and credits', mediaIntro: 'Images explain the project. Concept illustrations and existing project samples are labeled separately from evidence of an application running.',
    mediaItems: [
      ['Project illustrations', 'Generated for AuroraView with OpenAI image generation, October 2026. These are concept illustrations, not screenshots or proof of host integration.'],
      ['Gallery sample', 'Existing image from the main AuroraView repository, used under the project’s MIT license. It is a project sample rather than a new live-host acceptance test.'],
      ['Brand mark', 'AuroraView production vector mark, refined from the original project branding. Exported from native Blender Bézier curves. Text is outlined, with no embedded raster images or external font dependency.'],
      ['Architecture', 'Editable native draw.io source with English and Chinese SVG/PNG renders generated from the same graph model. The website also presents its layers as semantic HTML. SVG files embed the editable model; these renders do not claim a draw.io Desktop export.'],
      ['Typeface', 'Geist, self-hosted through @fontsource-variable/geist under the SIL Open Font License. The license accompanies the font.'],
    ],
    mediaLabels: ['Project concept PNG', 'Project-origin PNG', 'Interface case PNG', 'Original Gallery sample', 'Editable Blender master', 'Brand usage notes', 'Editable draw.io source', 'Architecture SVG', 'Architecture PNG', 'Architecture guide', 'Font license'],
    notFound: 'This page could not be found.', back: 'Return to AuroraView',
  },
  zh: {
    lang: 'zh-CN', locale: 'zh_CN', other: '/', otherLabel: 'English',
    title: 'AuroraView | 为创作软件构建 Web 界面',
    description: '用 AuroraView 为 DCC 工具构建 Web 界面。了解 Rust 核心、Python API、TypeScript SDK、宿主适配器、可运行示例和实际验证状态。',
    skip: '跳到正文', nav: ['为什么需要它', '技术架构', '项目生态', '开始使用'], theme: '切换颜色主题', light: '浅色', dark: '深色',
    heroLabel: 'AURORAVIEW / 开源项目', hero: 'Web 界面，<br>原生创作工具。',
    intro: '用前端技术和 AI 编程助手做好界面，再通过明确的适配边界，把工具带进原生创作软件。',
    start: '开始开发', explore: '查看项目生态', heroAlt: '概念插画：Web 界面与显式 Agent 契约连接原生创作工作区、扩展和打包分发。',
    concept: '概念示意，不是应用运行截图。',
    facts: [['Rust', '原生核心与 WebView 后端'], ['Python 3.7+', '面向现有 DCC 环境的 API'], ['TypeScript', '不绑定前端框架的 SDK']],
    whyTitle: 'Web 界面更容易做好，<br>宿主集成仍需认真处理。',
    whyIntro: 'AI 编程助手让 Web 界面更容易开发、尝试和打磨。但要把它带进 Maya、Houdini 或游戏引擎，仍然要处理原生窗口、UI 线程、应用 API 和打包分发。AuroraView 用统一框架连接这些工作，同时保留各层清楚的职责。',
    problems: [
      ['用成熟的 Web 生态开发', '用 HTML、CSS、React 或 Vue 开发面板、资产浏览器和管线工具。开发者与编程 Agent 都能使用熟悉的组件，同时把宿主操作独立维护。'],
      ['让通信有明确契约', '通过统一 SDK 调用宿主方法、接收事件。业务逻辑留在 Python 或原生适配器中，不散落在页面各处。'],
      ['遵循宿主的运行方式', '停靠、UI 线程、焦点和关闭流程由宿主适配负责。共享通信协议，不代表不同软件和平台具有相同的行为。'],
    ],
    whyAlt: '概念插画：左侧是重复的界面碎片，右侧是通过独立原生适配桥连接不同宿主的共享 Web 界面。',
    builtTitle: '已有的基础能力，都能从源码查证。',
    builtIntro: '主项目已有原生核心、Python 包、前端 SDK、CLI 和 Gallery 演示应用，也包含浏览器 API、扩展兼容层和打包工具。公开发布提供 wheel、命令行工具和 Gallery 构建产物。',
    galleryAlt: '已有 AuroraView Gallery 示例界面，包含导航、入门链接、代码示例和示例搜索。',
    galleryCaption: '主仓库中已有的 Gallery 示例图。它是项目素材，不代表本次新增的宿主验收结果。',
    sourceLabel: '阅读主项目源码', releaseLabel: '下载发布产物', galleryLabel: '查看 Gallery 源码',
    architectureTitle: '当前源码结构，<br>共享契约与宿主边界。',
    architectureIntro: '人通过 Web 界面操作工具，Agent 通过显式配置的 DCC-MCP 适配器进入。两条入口都遵循声明的通信契约；原生宿主始终拥有自己的生命周期和场景 API。',
    layers: [
      ['人和 Web 界面', 'HTML / CSS / React / Vue', '工具的显示，以及人直接操作的交互入口。'],
      ['声明的通信入口', 'TypeScript SDK / 可选的 DCC-MCP 注册', '页面调用与事件，以及显式配置的 Agent 工具和会话标识。'],
      ['AuroraView 核心与 API', 'Rust · IPC · Python / PyO3 · WebView 后端', '共享通信、窗口集成和后端抽象。'],
      ['可选的浏览器能力与扩展', 'Browser APIs · extension host · plugins', '可选能力与场景语义、宿主生命周期分开维护。'],
      ['原生宿主适配器', 'Python + Qt / 引擎原生集成', '宿主 API、停靠、UI 线程调度、焦点和关闭流程。'],
    ],
    hostBoundary: '应用拥有自己的 UI 线程和生命周期。',
    hostDetail: '基于 Qt 的 DCC 可以共享 Qt 集成。Blender、Unreal 和 Unity 需要各自的原生适配边界。Windows 上的 WebView2 对象始终由创建它的 STA 线程持有。',
    packBoundary: '打包与分发', packDetail: '构建时路径：为选定目标组织前端资源、Python 服务和原生启动。打包不替代运行时的宿主适配。',
    diagramSource: '下载可编辑架构图（.drawio）', architectureDocs: '阅读架构指南',
    agentTitle: '同一个工具，服务于人，<br>也为 Agent 提供明确入口。',
    agentIntro: '项目希望让工具既有好用的界面，也有主动声明的 Agent 调用入口。当前 DCC-MCP 集成提供了一组较小、可检查的基础契约。',
    humanTitle: '人通过界面操作', humanDetail: '按工作流设计控件和反馈。SDK 把页面连接到已经声明的宿主方法与事件。',
    agentPathTitle: 'Agent 调用已注册能力', agentDetail: '安装可选依赖 dcc-mcp-core，配置 AuroraViewAdapter，再启动服务。FileRegistry 注册让这个运行中的会话可以被发现。',
    agentTools: '当前适配器提供的工具', agentContext: '当前会话上下文包含窗口标题、URL、PID、CDP 端口和检测到的宿主。具体场景工具与上下文需要额外的宿主或 Skill 注册，不会从界面自动推导。',
    agentSource: '查看 DCC-MCP 集成源码', agentNote: '这里描述源码已经实现的契约；它与某个具体宿主内的 Agent 交互验收分别记录。',
    runtimeLabel: '计划 / 共享运行时', runtimeTitle: '同一套宿主能力，<br>页面与 Agent 都能使用。',
    runtimeIntro: '整合方向让 AuroraView 专注现代 Web 界面、渲染、前端事件和原生区域展示。薄集成层复用 DCC-MCP Core 已有的服务、工具与 Skill 注册、执行桥和生命周期。这个整合目前尚未交付。',
    runtimeLayers: [
      ['AuroraView', 'WebView · HTML 与资源 · 前端桥接 · 原生停靠', '负责界面与渲染。浏览器能力、扩展与构建时打包继续保留自己的边界。'],
      ['薄集成层 / 计划', '显式调用与事件 · 运行时附着 · 资源所有权', '将页面调用映射到已声明工具，并连接事件。页面与 Agent 应复用同一套宿主业务能力。'],
      ['DCC-MCP Core / 已有基础设施', 'Server / MCP · 工具与 Skill · 执行桥 · 生命周期', '通过公共契约复用已有宿主服务和调度。这是 AuroraView 的整合方向，不代表新的 API 已经交付。'],
      ['原生宿主适配器', '主线程调度 · 场景 API · 原生窗口 · 事件循环', '明确应用相关操作和宿主所有权。页面与 Agent 操作同一个宿主实例，并实际回读结果。'],
    ],
    runtimeOwnership: '优先附着，只释放自己拥有的资源。',
    runtimeOwnershipDetail: '优先附着已有的 DCC-MCP 宿主服务，缺少资源时再按需创建。面板关闭应释放自己的订阅、连接与任务，借用的宿主服务继续运行。创建者必须完整关闭自己拥有的资源，关闭操作需要可以重复调用。',
    runtimePending: '仍需实现与验证：版本兼容、事件和错误映射、服务所有权、重连、原生停靠和真实宿主交互。后端复用比例没有经过模块清单测算，不作为既定结论。',
    runtimeSource: '整合计划源图（.drawio）', runtimeSvg: '整合计划图（SVG）', runtimePng: '整合计划图（PNG）', runtimeCore: 'DCC-MCP Core 源码',
    capabilityTitle: '能力不止一个内嵌面板。',
    capabilities: [
      ['浏览器式 API', 'SDK 提供标签页、窗口、存储、运行时消息等浏览器相关接口。实际行为取决于后端和启用的功能。', 'packages/auroraview-sdk/src'],
      ['扩展与插件', '独立 crate 管理扩展生命周期、manifest、消息和浏览器 API 兼容。兼容性应逐项检查，不能理解为任何 Chrome 扩展都可原样运行。', 'crates/auroraview-extensions'],
      ['打包与分发', '打包层组织前端资源、Python 服务和原生应用启动。根据目标环境选择分发方式，并验证最终产物。', 'crates/auroraview-pack'],
    ],
    projectsTitle: '围绕实际宿主组织项目。',
    projectsIntro: '先了解核心，再选择目标软件的适配器和示例。下表将已有源码与真实宿主验证分开说明。',
    projectHeaders: ['项目', '职责', '当前证据'],
    projects: [
      ['auroraview', '核心、Python API、SDK、CLI 与 Gallery', '已有源码和公开发布产物', links.source],
      ['auroraview-maya', 'Maya 宿主适配器', '已有适配源码；宿主验收需对应具体版本', 'https://github.com/try-auroraview/auroraview-maya'],
      ['auroraview-maya-outliner', '独立的 Maya 场景树教学项目', '已有源码；教程更新与宿主验收正在推进', links.mayaOutliner],
      ['auroraview-houdini', 'Houdini 宿主适配器', '已有适配源码；宿主验收需对应具体版本', 'https://github.com/try-auroraview/auroraview-houdini'],
      ['auroraview-nuke', 'Nuke 调度器与宿主适配器', '已有适配源码；宿主验收需对应具体版本', 'https://github.com/try-auroraview/auroraview-nuke'],
      ['auroraview-blender', 'Blender 原生插件与实验性 WebView 路径', '实验性集成；原生 WebView 停靠验收单独记录', 'https://github.com/try-auroraview/auroraview-blender'],
      ['auroraview-unreal', 'Unreal Engine 集成', '实验性集成；原生构建与交互验收分别记录', 'https://github.com/try-auroraview/auroraview-unreal'],
    ],
    evidenceTitle: '怎样理解这里的“已验证”',
    evidence: '源码、自动化测试、原生构建、真实宿主启动和交互演示是不同的里程碑。有仓库或单测通过，不能直接说明已完整支持某个宿主。采用前，请查看适配器记录的具体环境。',
    evidenceDate: '项目目录核对日期：2026 年 10 月 8 日。较新的验证结果请查看各仓库记录。',
    startTitle: '先在独立窗口中开发，<br>再把工具带进宿主。',
    startIntro: '先让前端在独立窗口中运行，再选择宿主适配器。把宿主操作放在明确的 API 后面，并在目标软件里验证完整生命周期。',
    installLabel: '1 / 安装 Python 包', codeLabel: '2 / 加载本地前端', copy: '复制', copied: '已复制', copyFailed: '请选中代码并手动复制。',
    prerequisites: '使用目标宿主对应的 Python 环境。Windows 需要 WebView2 Runtime，Linux 需要 WebKitGTK 系统依赖。Qt 集成还需满足对应宿主要求。',
    docLabel: '查看安装与平台要求',
    tutorialsTitle: '从真实工具学习。',
    tutorialsIntro: '教学项目与宿主适配器分开维护。每个示例应写清前置环境、启动命令、预期行为和验证范围，方便以后增加其他宿主的教程。',
    tutorials: [
      ['Maya Outliner', '独立维护的 Maya 场景树案例。可运行教程正在更新，真实宿主内的交互验收仍待完成。', '查看教学项目', links.mayaOutliner],
      ['核心示例', '独立窗口、方法调用、事件和 Qt 集成的实际用法。', '浏览示例源码', links.examples],
      ['Gallery', '了解已有演示应用，以及界面背后的实现代码。', '查看 Gallery 项目', links.gallery],
    ],
    contributing: '正在开发宿主集成？', contribution: '让共享协议保持简洁。把宿主生命周期和打包放在适配器里，并提供可运行示例和明确的验证记录。', contributionLink: '在 GitHub 参与开发',
    footer: '为创作软件构建开源 Web 界面。', credits: '图片来源与说明', privacy: '本站不使用分析追踪或第三方请求。字体和图片均随站点托管。',
    mediaTitle: '图片来源与说明', mediaIntro: '图片用于解释项目。概念插画与已有项目示例均单独标注，不代替实际应用运行的验收证据。',
    mediaItems: [
      ['项目插画', '2026 年 10 月通过 OpenAI 图像生成功能为 AuroraView 制作。这些是概念插画，不是运行截图，也不是宿主集成通过的证据。'],
      ['Gallery 示例', '来自 AuroraView 主仓库的已有图片，按该项目的 MIT 许可证使用。它是项目示例素材，不代表本次新的真实宿主验收。'],
      ['品牌标志', '基于原有项目品牌打磨的 AuroraView 正式矢量标志，从 Blender 原生贝塞尔曲线导出。文字已经转为路径，不包含内嵌位图或外部字体依赖。'],
      ['技术架构图', '提供原生 draw.io 可编辑源文件，以及由同一图模型生成的中英文 SVG 和 PNG。网页也用语义 HTML 呈现这些层次。SVG 内嵌可编辑模型；这些渲染不宣称由 draw.io Desktop 导出。'],
      ['字体', '通过 @fontsource-variable/geist 随站点托管 Geist 字体，遵循 SIL Open Font License，许可证文件一并提供。'],
    ],
    mediaLabels: ['完整理念 PNG', '项目缘起 PNG', '界面案例 PNG', 'Gallery 原始示例图', '可编辑 Blender 源文件', '品牌使用说明', '可编辑 draw.io 源文件', '架构 SVG', '架构 PNG', '架构文档', '字体许可证'],
    notFound: '没有找到这个页面。', back: '返回 AuroraView',
  },
};

export const snippets = {
  install: 'pip install auroraview',
  python: 'from auroraview import run_desktop\n\nrun_desktop(\n    title="My pipeline tool",\n    url="http://localhost:3000",\n    width=1024,\n    height=768,\n)',
};
