const source = 'https://github.com/try-auroraview/auroraview/blob/main/';
const tree = 'https://github.com/try-auroraview/auroraview/tree/main/';

export const principles = {
  en: {
    title: 'How AuroraView works',
    intro: 'A page is the interface. A declared API is the boundary. The host executes its scene operations and returns observable state. This page follows the main Python / Rust integration and the original AuroraView layer diagram. A separate native adapter may reuse the bridge contract with its own implementation; inspect its host record.',
    originalTitle: 'The original layer model', originalCaption: 'Existing architecture image from the main AuroraView repository. It explains the Python → PyO3 → Rust → system WebView layering; individual host support still needs its own evidence.',
    originalAlt: 'Original AuroraView architecture: DCC software calls the Python package and PyO3 bindings, which use the Rust core and system-native WebView engines.',
    flowTitle: 'From a click to a scene result',
    flow: [
      ['The page names a capability', 'A click handler calls a declared method through the SDK. call() returns a Promise; on() subscribes to host events. The page controls presentation and feedback.', 'AuroraViewClient: call / on / emit', source + 'packages/auroraview-sdk/src/core/bridge.ts'],
      ['The bridge carries the request', 'IPC carries the method, parameters, and request identity through the native bridge. Rust provides protocol and backend boundaries; PyO3 connects the Python-facing implementation.', 'Shared IPC builder and Python bindings', tree + 'crates/auroraview-core/src/builder'],
      ['The host scheduler executes the operation', 'bind_call() or bind_api() exposes a callable. A configured set_call_dispatcher(), or the registered host dispatcher, schedules it on the permitted thread. The DCC-mode path rejects an unsafe fallback; a lock alone does not grant scene-thread access.', 'WebViewApiMixin: bind_call / bind_api / set_call_dispatcher', source + 'python/auroraview/core/mixins/api.py'],
      ['Read back the resulting scene state', 'The host function performs the operation, then reads the state needed by the tool: selection, object identity, hierarchy, or another declared result. A scene readback is application logic supplied by the host integration.', 'Host adapters and end-to-end examples', '/ecosystem/'],
      ['Return a result or publish an event', 'The request result settles its Promise; host changes can also be emitted as events. Python emit() uses the native command target, and the SDK routes window.auroraview.trigger() events to subscribers.', 'WebViewEventsMixin and SDK events', source + 'python/auroraview/core/mixins/events.py'],
      ['The UI shows confirmed state', 'Update the interface from returned data and subscribed events. Show structured errors and release subscriptions when the tool closes. A successful message send is separate from the scene result the tool reads back.', 'SDK event subscriptions and unsubscribe contract', source + 'packages/auroraview-sdk/src/core/events.ts'],
    ],
    communicationTitle: 'Three directions, one bridge',
    communicationIntro: 'Use a call when you need a result, and an event when you do not. The low-level window.auroraview bridge and the TypeScript SDK share this direction model.',
    communicationHeaders: ['Direction', 'Page API', 'Python boundary'],
    communication: [
      ['Page → host, request / response', 'call(method, params, options) → Promise', 'bind_call(method) / bind_api(...)'],
      ['Page → host, fire and forget', 'send_event(event, detail); SDK client.emit(...)', '@webview.on(event)'],
      ['Host → page, notification', 'on(event, handler) → unsubscribe', 'webview.emit(event, payload) → trigger(...)'],
    ],
    communicationNote: 'trigger() delivers events inside JavaScript; calling it in a page does not send a message to Python. Call results use the internal __auroraview_call_result event with id, ok, and result or error. Save the function returned by on() and invoke it to unsubscribe.',
    dispatchNote: 'The current call handler captures the request identity, schedules invocation, validates a JSON result, and reports structured errors. Pending-call generations prevent stale callbacks from completing after close. Event dispatch has its own owner queue and disconnect guards; synchronous closing veto callbacks need a separate lifecycle path.',
    communicationSource: 'Read the communication guide',
    stackTitle: 'What each layer owns',
    stack: [
      ['Frontend SDK', 'Framework-agnostic calls, events, readiness, feature detection, and browser-oriented interfaces. Use React, Vue, or plain JavaScript around that public boundary.', 'TypeScript SDK exports', source + 'packages/auroraview-sdk/src/index.ts'],
      ['Python API and PyO3', 'The Python package binds host operations and integrates with the host event loop. PyO3 exposes Rust functionality to Python. Qt integrations retain Qt’s event-loop ownership.', 'Python API / Rust bindings', tree + 'src/bindings'],
      ['Rust core and backend abstraction', 'Shared protocol and backend interfaces separate communication from native rendering. The current workspace uses Wry with the wry-builder feature; Windows DCC embedding also has a direct WebView2 path.', 'WebViewBackend trait', source + 'crates/auroraview-core/src/backend/traits.rs'],
      ['Native engines and docking', 'The system-engine model is WebView2 on Windows, WKWebView on macOS, and WebKitGTK on Linux. Actual engine availability and native docking depend on the chosen backend and host adapter. WebView2 objects stay on their owning STA thread.', 'Windows DCC WebView implementation', source + 'crates/auroraview-dcc/src/webview.rs'],
    ],
    engineNote: 'Current main Cargo configuration uses Wry/system WebView and WebView2 dependencies. It does not define a unified CEF feature. Separate host experiments or newer CEF work must be evaluated as their own implementation and acceptance path.',
    engineSource: 'Inspect workspace dependencies and features',
    agentTitle: 'The same capability, with an explicit Agent contract',
    agentDetail: 'An Agent entry point declares discovery, parameters, results, errors, and host scope. The current AuroraViewAdapter exposes eval_js, screenshot, load_url, and load_html with panel/session context. Scene tools and scene semantics require explicit host or Skill registration; they do not appear automatically from a web page.',
    agentSource: 'Current adapter declarations',
    lifecycleTitle: 'Rendering lifetime and service lifetime are different',
    lifecycleDetail: 'A native panel owns its presentation, connections, subscriptions, and tasks. The proposed shared-runtime integration prefers attaching to an existing DCC-MCP service and execution bridge. Closing a panel must leave borrowed host services running; creators must close the resources they own. That integration remains planned and still needs compatibility and real-host acceptance.',
    lifecycleLink: 'Read the proposed shared-runtime model',
    modulesTitle: 'Extend and distribute deliberately',
    modules: [
      ['Browser-oriented APIs', 'Tabs, windows, storage, runtime messages, and feature detection are exposed through SDK surfaces. Check the backend and enabled feature rather than assuming a complete browser implementation.', 'SDK browser and feature APIs', tree + 'packages/auroraview-sdk/src'],
      ['Extensions and plugins', 'Dedicated code handles manifests, extension lifecycle, messaging, and API compatibility. Compatibility is API-specific and needs validation for the extension you ship.', 'auroraview-extensions', tree + 'crates/auroraview-extensions'],
      ['Pack and distribution', 'Packing combines frontend assets, services, configuration, and native startup into a target artifact. It is a build-time concern; deployment still needs the target’s engine, installation, and lifecycle checks.', 'auroraview-pack', tree + 'crates/auroraview-pack'],
    ],
    quickTitle: 'A small contract to learn first', quickDetail: 'Start with a standalone frontend and run_desktop(). Bind one host operation, subscribe to one event, and read back a result. Then choose the native host adapter and use its installation and lifecycle requirements.', quickLink: 'Open the quick start', matrixLink: 'Inspect the host matrix', back: 'Return to the project guide',
  },
  zh: {
    title: 'AuroraView 的工作原理',
    intro: '页面负责界面，显式 API 划定边界，宿主执行场景操作并返回可观察状态。本页沿用 AuroraView 原有架构图，说明主项目 Python / Rust 集成路径。独立原生适配器可以用自己的实现复用桥接契约，具体边界请查看对应宿主记录。',
    originalTitle: '原有的分层模型', originalCaption: '来自 AuroraView 主仓库的已有架构图，用来说明 Python → PyO3 → Rust → 系统 WebView 的层次。各宿主支持仍需独立证据。',
    originalAlt: 'AuroraView 原架构图：DCC 软件调用 Python 包与 PyO3 绑定，再连接 Rust 核心和系统原生 WebView 引擎。',
    flowTitle: '从一次点击，到实际场景结果',
    flow: [
      ['页面明确要调用的能力', '点击处理函数通过 SDK 调用已声明的方法。call() 返回 Promise，on() 订阅宿主事件。页面负责显示和交互反馈。', 'AuroraViewClient：call / on / emit', source + 'packages/auroraview-sdk/src/core/bridge.ts'],
      ['桥接层传递请求', 'IPC 将方法名、参数和请求标识送入原生桥。Rust 提供协议与后端边界，PyO3 将 Python 使用层连接到 Rust 实现。', '共享 IPC builder 与 Python 绑定', tree + 'crates/auroraview-core/src/builder'],
      ['宿主调度器执行操作', '用 bind_call() 或 bind_api() 暴露函数，由配置的 set_call_dispatcher() 或已注册的宿主调度器将调用排入允许的线程。DCC 模式会拒绝不安全的回退路径；加锁本身不能获得场景线程访问权。', 'WebViewApiMixin：bind_call / bind_api / set_call_dispatcher', source + 'python/auroraview/core/mixins/api.py'],
      ['回读操作后的场景状态', '宿主函数执行操作后，读取工具需要的状态，例如选择、对象身份、层级或其他明确结果。场景回读属于宿主集成提供的业务逻辑。', '宿主适配与端到端示例', '/zh/ecosystem/'],
      ['返回结果或发送事件', '请求结果完成对应 Promise，宿主变化也可通过事件发送。Python emit() 使用原生命令目标，SDK 再把 window.auroraview.trigger() 事件交给订阅者。', 'WebViewEventsMixin 与 SDK 事件', source + 'python/auroraview/core/mixins/events.py'],
      ['界面显示已确认的状态', '用返回数据和订阅事件更新界面，显示结构化错误，并在工具关闭时释放订阅。消息发送成功与工具实际回读到的场景结果是两项证据。', 'SDK 事件订阅与取消订阅契约', source + 'packages/auroraview-sdk/src/core/events.ts'],
    ],
    communicationTitle: '一套桥接，三个明确方向',
    communicationIntro: '需要返回结果时使用调用，不需要结果时使用事件。底层 window.auroraview 与 TypeScript SDK 遵循同样的方向模型。',
    communicationHeaders: ['方向', '页面 API', 'Python 边界'],
    communication: [
      ['页面 → 宿主，请求 / 响应', 'call(method, params, options) → Promise', 'bind_call(method) / bind_api(...)'],
      ['页面 → 宿主，即发即忘', 'send_event(event, detail)；SDK client.emit(...)', '@webview.on(event)'],
      ['宿主 → 页面，事件通知', 'on(event, handler) → 取消订阅函数', 'webview.emit(event, payload) → trigger(...)'],
    ],
    communicationNote: 'trigger() 只在 JavaScript 内投递事件，页面主动调用它不会发送消息到 Python。调用结果通过内部 __auroraview_call_result 事件传递 id、ok，以及 result 或 error。保存 on() 返回的函数，在结束时调用以取消订阅。',
    dispatchNote: '当前调用处理器保存请求标识、调度执行、验证 JSON 返回值并报告结构化错误。待处理调用的代际检查防止关闭后旧回调继续完成。事件调度有自己的所有者队列与断开保护；同步 closing 否决回调需要单独的生命周期路径。',
    communicationSource: '阅读双向通信文档',
    stackTitle: '每一层负责什么',
    stack: [
      ['前端 SDK', '提供不绑定框架的调用、事件、就绪状态、功能检测和浏览器式接口。可在公共边界外使用 React、Vue 或原生 JavaScript。', 'TypeScript SDK 导出', source + 'packages/auroraview-sdk/src/index.ts'],
      ['Python API 与 PyO3', 'Python 包绑定宿主操作，并对接宿主事件循环。PyO3 将 Rust 功能暴露给 Python。Qt 集成继续由 Qt 拥有事件循环。', 'Python API / Rust 绑定', tree + 'src/bindings'],
      ['Rust 核心与后端抽象', '共享协议和后端接口将通信与原生渲染分开。当前 workspace 使用 Wry 与 wry-builder，Windows DCC 内嵌也有直接 WebView2 路径。', 'WebViewBackend trait', source + 'crates/auroraview-core/src/backend/traits.rs'],
      ['原生引擎与停靠', '系统引擎模型对应 Windows WebView2、macOS WKWebView 和 Linux WebKitGTK。实际引擎能力与原生停靠取决于选用后端及宿主适配器。WebView2 对象始终留在创建它的 STA 线程。', 'Windows DCC WebView 实现', source + 'crates/auroraview-dcc/src/webview.rs'],
    ],
    engineNote: '当前 main 的 Cargo 配置使用 Wry / 系统 WebView 与 WebView2 依赖，没有定义统一 CEF feature。单独的宿主实验或较新的 CEF 工作，需要按各自实现与验收路径评估。',
    engineSource: '查看 workspace 依赖与 feature',
    agentTitle: '同一套能力，需要明确的 Agent 契约',
    agentDetail: 'Agent 入口要声明发现方式、参数、结果、错误和宿主范围。当前 AuroraViewAdapter 提供 eval_js、screenshot、load_url、load_html，以及面板和会话上下文。场景工具与语义需要显式的宿主或 Skill 注册，不会从网页自动产生。',
    agentSource: '当前适配器的工具声明',
    lifecycleTitle: '渲染生命周期与服务生命周期分别维护',
    lifecycleDetail: '原生面板拥有自己的显示区域、连接、订阅与任务。计划中的共享运行时优先附着已有 DCC-MCP 服务与执行桥。面板关闭后，借用的宿主服务继续运行；创建者负责关闭自己拥有的资源。这个整合仍属计划，还需要兼容性与真实宿主验收。',
    lifecycleLink: '查看共享运行时整合计划',
    modulesTitle: '有边界地扩展与分发',
    modules: [
      ['浏览器式 API', 'SDK 提供标签页、窗口、存储、运行时消息与功能检测。需要按后端和启用功能核对，不能据此假定完整浏览器实现。', 'SDK 浏览器与功能接口', tree + 'packages/auroraview-sdk/src'],
      ['扩展与插件', '独立模块处理 manifest、扩展生命周期、消息与 API 兼容。兼容性需要按实际发布的扩展逐项验证。', 'auroraview-extensions', tree + 'crates/auroraview-extensions'],
      ['打包与分发', '打包将前端资源、服务、配置与原生启动组织为目标产物。这属于构建时职责，部署仍需检查目标引擎、安装与生命周期。', 'auroraview-pack', tree + 'crates/auroraview-pack'],
    ],
    quickTitle: '先掌握一套小而清楚的契约', quickDetail: '先用独立前端与 run_desktop() 开始，绑定一个宿主操作、订阅一个事件并回读结果，再选择原生宿主适配器，遵循对应安装和生命周期要求。', quickLink: '打开快速开始', matrixLink: '查看宿主矩阵', back: '返回项目指南',
  },
};
